setup $PWD/.bbox erased trailing spaces

diff --git a/bin/bbox b/bin/bbox
--- a/bin/bbox
+++ b/bin/bbox
@@ -7,7 +7,7 @@ function help() {
     echo "bbox - bixin's micro services toolkit"
     echo "usage: bbox <command> [args] [options]"
     echo 'commands'
-    echo ' init                      - generate ticket.json'
+    echo ' init                      - generate .bbox/ticket.json'
     echo ' start <modspec> [modspec] - start rpc server'
     echo ' httpd <modspec>           - start httpd and load module'
     echo ' metrics                   - prometheus metrics url'
@@ -26,13 +26,14 @@ function genkey() {
         echo 'you must provide a key prefix, ie. server' >&2
         exit 1
     fi
+    cert_root=./.bbox/certs/$prefix
 
-    mkdir -p certs/$prefix
-    if [ -f certs/$prefix/$prefix.key ]; then
-        echo The private key certs/$prefix/$prefix.key already exist! It is dangrous to overwrite it.
+    mkdir -p $cert_root
+    if [ -f $cert_root/$prefix.key ]; then
+        echo The private key $cert_root/$prefix.key already exist! It is dangrous to overwrite it.
         exit 1
     fi
-    cd certs/$prefix
+    cd $cert_root
 
     echo generating privkey
     openssl genrsa -des3 -passout pass:x -out $prefix.pass.key 2048
@@ -47,7 +48,15 @@ function genkey() {
     openssl pkcs12 -export -in $prefix.crt -inkey $prefix.key -out $prefix.p12
 
     cd ../..
-    echo keys generated to ./certs/$prefix
+    echo keys generated to ./$cert_root
+}
+
+function check-ticket() {
+    lang=`$PY3 -m aiobbox.tools.printticket language`
+    if [ $? -ne 0 ]; then
+        echo 'ticket not found or not correct, run bbox init first' >&2
+        exit 1
+    fi
 }
 
 case "$1" in
@@ -55,8 +64,9 @@ case "$1" in
         exec $PY3 -m aiobbox.tools.initprj "${@:2}"
         ;;
     start)
+        check-ticket
         lang=`$PY3 -m aiobbox.tools.printticket language`
-        if [ $lang == 'python3' ]; then
+        if [ "x${lang}" == 'xpython3' ]; then
             exec $PY3 -m aiobbox.tools.startbox "${@:2}"
         else
             # TODO: support nodejs
@@ -65,8 +75,9 @@ case "$1" in
         fi
         ;;
     httpd)
+        check-ticket
         lang=`$PY3 -m aiobbox.tools.printticket language`
-        if [ $lang == 'python3' ]; then
+        if [ "x${lang}" == 'xpython3' ]; then
             exec $PY3 -m aiobbox.tools.starthttpd "${@:2}"
         else
             # TODO: support nodejs
@@ -78,8 +89,9 @@ case "$1" in
         exec bbox httpd aiobbox.services.metrics "${@:2}"
         ;;
     run)
+        check-ticket
         lang=`$PY3 -m aiobbox.tools.printticket language`
-        if [ $lang == 'python3' ]; then
+        if [ "x$lang" == 'xpython3' ]; then
             exec $PY3 -m aiobbox.tools.runtask "${@:2}"
         else
             # TODO: support nodejs
